//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ID_Заявки { get; set; }
        public int ID_Участка { get; set; }
        public int ID_Пользователя { get; set; }
        public int ID_Деятельности { get; set; }
    
        public virtual Деятельность_на_ЗУ Деятельность_на_ЗУ { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Участки Участки { get; set; }
    }
}
